// <auto-generated />
using System;
using Kds.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kds.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717182944_SequenceEntity")]
    partial class SequenceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kds.Domain.Entities.Kot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("KotCancelledOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("kot_cancelled_on");

                    b.Property<DateTime?>("KotCompletedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("kot_completed_on");

                    b.Property<long>("KotNo")
                        .HasColumnType("bigint")
                        .HasColumnName("kot_no");

                    b.Property<DateTime?>("KotPreparationStartedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("kot_preparation_started_on");

                    b.Property<DateTime?>("KotReadyOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("kot_ready_on");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("OrderId");

                    b.ToTable("kot", (string)null);
                });

            modelBuilder.Entity("Kds.Domain.Entities.MenuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("menu_item_name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("menu_item", (string)null);
                });

            modelBuilder.Entity("Kds.Domain.Entities.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("TableNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("table_number");

                    b.HasKey("OrderId")
                        .HasName("PRIMARY");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("Kds.Domain.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_on");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("KotId")
                        .HasColumnType("bigint")
                        .HasColumnName("kot_id");

                    b.Property<long>("MenuItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_item_id");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("KotId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("Kds.Domain.Entities.Sequence", b =>
                {
                    b.Property<long>("SequenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SequenceId"));

                    b.Property<string>("SequenceGroup")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sequence_group");

                    b.Property<string>("SequenceKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sequence_key");

                    b.Property<long>("SequenceValue")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_value");

                    b.HasKey("SequenceId");

                    b.ToTable("sequence", (string)null);
                });

            modelBuilder.Entity("Kds.Domain.Entities.Kot", b =>
                {
                    b.HasOne("Kds.Domain.Entities.Order", "RestaurantOrder")
                        .WithMany("Kots")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RestaurantOrder");
                });

            modelBuilder.Entity("Kds.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Kds.Domain.Entities.Kot", "Kot")
                        .WithMany("OrderItems")
                        .HasForeignKey("KotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kds.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kds.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kot");

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Kds.Domain.Entities.Kot", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Kds.Domain.Entities.Order", b =>
                {
                    b.Navigation("Kots");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
